/**
 * Vend CI — the structural-backstop Dagger module.
 *
 * This module is the *independent inspection* layer for the structural/mechanical
 * defect class only (compile, type, test, lint). It is a separate program from the
 * app: it imports NOTHING from the app, and the app imports nothing from it. The
 * only contract between them is the app's `bun run check:*` command surface.
 *
 * THE CENTRAL RULE: Dagger invokes; it never defines. Check *logic* lives in the
 * app's `bun run check:*` scripts. Each gate here is a thin trigger-and-report
 * sub-class that spins a container and calls one of those scripts — never
 * reimplements it.
 *
 * THE ROUTER CONTRACT: one gate = one sub-class = one file. TypeScript cannot split
 * this main module file, so `index.ts` stays a *thin router*: every gate is a single
 * `@func()` that delegates to its own `src/<gate>.ts`. If this file grows past
 * routing, that is the god-object mess — extract to a sub-class file.
 *
 * First gate (T-002-01-02): `test()` is wired — it returns the `Test` sub-object
 * (`src/test.ts`), which runs `bun run check:test` in a Bun container. The router
 * stays thin: one `@func()` per gate, each a one-line return of its own sub-class
 * (the next gates — lint, typecheck, consistency — follow the identical shape).
 * The `sdk/` client is generated by codegen at the pinned engine (a reviewed step)
 * and is gitignored — `@dagger.io/dagger` resolves to it via tsconfig `paths`, not
 * an npm dependency.
 */
import { object, func } from "@dagger.io/dagger"
import { Test } from "./test"

@object()
export class Ci {
  /** Structural gate: the app test suite, run as independent container inspection. */
  @func()
  test(): Test {
    return new Test()
  }
}
