/**
 * Vend CI — the structural-backstop Dagger module.
 *
 * This module is the *independent inspection* layer for the structural/mechanical
 * defect class only (compile, type, test, lint). It is a separate program from the
 * app: it imports NOTHING from the app, and the app imports nothing from it. The
 * only contract between them is the app's `bun run check:*` command surface.
 *
 * THE CENTRAL RULE: Dagger invokes; it never defines. Check *logic* lives in the
 * app's `bun run check:*` scripts. Each gate here is a thin trigger-and-report
 * sub-class that spins a container and calls one of those scripts — never
 * reimplements it.
 *
 * THE ROUTER CONTRACT: one gate = one sub-class = one file. TypeScript cannot split
 * this main module file, so `index.ts` stays a *thin router*: every gate is a single
 * `@func()` that delegates to its own `src/<gate>.ts`. If this file grows past
 * routing, that is the god-object mess — extract to a sub-class file.
 *
 * Bootstrap shell (T-002-01-01): the module exists, on the Node runtime, with the
 * engine pinned to v0.21.4 in `dagger.json`, and NO gate logic yet. The first gate,
 * `test()` (delegating to `src/test.ts` → `bun run check:test`), is added by
 * T-002-01-02. The `sdk/` client is generated by codegen at the pinned engine (a
 * reviewed step) and is gitignored — `@dagger.io/dagger` resolves to it via tsconfig
 * `paths`, not an npm dependency.
 */
import { object } from "@dagger.io/dagger"

@object()
export class Ci {}
